import * as THREE from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{makeProfile,buildSweep}from'./sweepGeometry.js';
const host=document.querySelector('#viewport'),scene=new THREE.Scene();scene.background=new THREE.Color(0x22262d);const camera=new THREE.PerspectiveCamera(50,1,.01,1000);camera.position.set(7,7,7);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.enabled=false;scene.add(new THREE.HemisphereLight(0xffffff,0x444444,2.2));const dl=new THREE.DirectionalLight(0xffffff,2);dl.position.set(5,8,4);scene.add(dl);scene.add(new THREE.GridHelper(20,40,0x657080,0x343a44));
const $=s=>document.querySelector(s),status=$('#status'),ray=new THREE.Raycaster(),ndc=new THREE.Vector2();let items=[],current=null,drawing=false,mode='draw',selected=null,undo=[],redo=[];
const mat=()=>new THREE.MeshStandardMaterial({color:0xd7dde7,roughness:.55,metalness:.05,side:THREE.DoubleSide,wireframe:$('#wire').checked});
function snapshot(){return items.map(x=>({raw:x.raw.map(p=>p.toArray()),settings:{...x.settings}}));}function restore(s){items.forEach(x=>{scene.remove(x.mesh);x.mesh.geometry.dispose();x.mesh.material.dispose()});items=[];selected=null;s.forEach(d=>addItem(d.raw.map(a=>new THREE.Vector3(...a)),d.settings));updateStatus();}function checkpoint(){undo.push(snapshot());if(undo.length>30)undo.shift();redo=[];}
function plane(){const v=$('#plane').value;return v==='XY'?new THREE.Plane(new THREE.Vector3(0,0,1),0):v==='YZ'?new THREE.Plane(new THREE.Vector3(1,0,0),0):new THREE.Plane(new THREE.Vector3(0,1,0),0);}function eventRay(e){const r=renderer.domElement.getBoundingClientRect();ndc.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(ndc,camera);}function point(e){eventRay(e);const p=new THREE.Vector3();return ray.ray.intersectPlane(plane(),p)?p:null;}
function settings(){return{profile:$('#profile').value,size:+$('#size').value,smooth:+$('#smooth').value,sides:+$('#sides').value,caps:$('#caps').checked};}function sample(raw,k){if(raw.length<2)return raw;return new THREE.CatmullRomCurve3(raw,false,'centripetal',.5).getPoints(Math.max(2,Math.min(500,raw.length*k)));}function rebuild(x){x.mesh.geometry.dispose();const p=sample(x.raw,x.settings.smooth);x.mesh.geometry=buildSweep(p,makeProfile(x.settings.profile,x.settings.size,x.settings.sides),{caps:x.settings.caps});x.mesh.material.wireframe=$('#wire').checked;}function addItem(raw,st=settings()){const mesh=new THREE.Mesh(new THREE.BufferGeometry(),mat()),x={raw,settings:{...st},mesh};items.push(x);scene.add(mesh);rebuild(x);return x;}function select(x){if(selected)selected.mesh.material.emissive.setHex(0);selected=x;if(selected)selected.mesh.material.emissive.setHex(0x29405f);updateStatus();}function updateStatus(){const verts=items.reduce((n,x)=>n+(x.mesh.geometry.getAttribute('position')?.count||0),0);status.textContent=`${items.length} sweep${items.length===1?'':'s'} • ${verts} vertices${selected?' • selected':''}`;}
function setMode(m){mode=m;controls.enabled=m==='orbit';$('#drawBtn').classList.toggle('active',m==='draw');$('#orbitBtn').classList.toggle('active',m==='orbit');}
renderer.domElement.addEventListener('pointerdown',e=>{if(mode==='orbit'){eventRay(e);const hits=ray.intersectObjects(items.map(x=>x.mesh),false);select(hits.length?items.find(x=>x.mesh===hits[0].object):null);return;}checkpoint();drawing=true;current=addItem([],settings());const p=point(e);if(p)current.raw.push(p);renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!drawing||mode!=='draw')return;const p=point(e);if(p&&(!current.raw.length||p.distanceTo(current.raw.at(-1))>.035)){current.raw.push(p);rebuild(current);updateStatus();}});renderer.domElement.addEventListener('pointerup',()=>{drawing=false;if(current&&current.raw.length<2){scene.remove(current.mesh);items=items.filter(x=>x!==current)}current=null;updateStatus();});
$('#drawBtn').onclick=()=>setMode('draw');$('#orbitBtn').onclick=()=>setMode('orbit');['profile','size','smooth','sides','caps'].forEach(id=>$('#'+id).addEventListener('input',()=>{$('#sizeOut').value=(+$('#size').value).toFixed(2);$('#sidesOut').value=$('#sides').value;}));$('#wire').oninput=()=>items.forEach(rebuild);$('#undoBtn').onclick=()=>{if(!undo.length)return;redo.push(snapshot());restore(undo.pop())};$('#redoBtn').onclick=()=>{if(!redo.length)return;undo.push(snapshot());restore(redo.pop())};$('#deleteBtn').onclick=()=>{if(!selected)return;checkpoint();scene.remove(selected.mesh);selected.mesh.geometry.dispose();selected.mesh.material.dispose();items=items.filter(x=>x!==selected);selected=null;updateStatus()};$('#clearBtn').onclick=()=>{if(!items.length)return;checkpoint();restore([])};
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();updateStatus();renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});